ALTER TABLE pengajuan_sidang
  MODIFY COLUMN status ENUM(
    'DRAFT','SUBMITTED','NEED_REVISION',
    'VERIFIED',
    'WAITING_FOR_DISPOSISI','WAITING_FOR_SURAT','COMPLETED',
    'REJECTED'
  ) NOT NULL DEFAULT 'DRAFT';

ALTER TABLE pengajuan_sidang_kaprodi
  MODIFY COLUMN status ENUM(
    'DRAFT','SUBMITTED','NEED_REVISION','VALID','REJECTED',
    'DISPOSISI_SENT','COMPLETED'
  ) NOT NULL DEFAULT 'DRAFT';

ALTER TABLE pengajuan_sidang_files
  MODIFY COLUMN file_type ENUM(
    'JUDUL_LUAR','JUDUL_DALAM','PERSETUJUAN_UJIAN',
    'ABSTRAK','KATA_PENGANTAR','DAFTAR_ISI',
    'DAFTAR_TABEL','DAFTAR_GAMBAR','DAFTAR_LAMPIRAN',
    'BAB_1_5','DAFTAR_PUSTAKA','RIWAYAT_HIDUP',
    'HALAMAN_LAMPIRAN','INDEKS','SURAT_KETERANGAN',
    'SURAT_PERNYATAAN_TIDAK_PLAGIAT',
    'LEMBAR_USULAN_PENGUJI','LEMBAR_PERMOHONAN_UJIAN',
    'PAS_FOTO','KTM','BUKTI_PEMBAYARAN',
    'LEMBAR_KONSULTASI_JURNAL','KARTU_KONSULTASI_SKRIPSI',
    'SK_PENUNJUKAN_PEMBIMBING','REKAP_NILAI',
    'SURAT_PERNYATAAN_PENYELESAIAN','SURAT_PERNYATAAN_PERBAIKAN',
    'SURAT_PERNYATAAN_KELENGKAPAN',
    'KHS_1','KHS_2','KHS_3','KHS_4','KHS_5','KHS_6','KHS_7','KHS_8',
    'FOTOCOPY_KONVERSI','BUKTI_HADIR_SIDANG','KARTU_KONSULTASI_PA',
    'KARTU_PRAKTIKUM','SERTIFIKAT_POINT',
    'SURAT_UNDANGAN_SIDANG'
  ) NOT NULL;
