ALTER TABLE sidang
  MODIFY COLUMN hasil_sidang ENUM('LULUS','TIDAK_LULUS','GAGAL') NULL;

ALTER TABLE sidang_hasil_penilaian
  MODIFY COLUMN hasil_sidang ENUM('LULUS','TIDAK_LULUS','GAGAL') NULL;

ALTER TABLE skripsi
  MODIFY COLUMN status ENUM('IN_PROGRESS','COMPLETED','GAGAL') NOT NULL DEFAULT 'IN_PROGRESS';
