CREATE TABLE IF NOT EXISTS staf (
  usr_id VARCHAR(50) PRIMARY KEY,
  nama VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_staf_username (username)
);
