CREATE TABLE fakultas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255) NOT NULL,
  kode VARCHAR(20) NOT NULL,
  dekan_nidn VARCHAR(20) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_fakultas_kode (kode)
);

ALTER TABLE program_studi
  ADD COLUMN kode VARCHAR(20) NOT NULL DEFAULT '' AFTER nama,
  ADD COLUMN fakultas_id BIGINT UNSIGNED DEFAULT NULL AFTER kode,
  ADD CONSTRAINT fk_ps_fakultas FOREIGN KEY (fakultas_id) REFERENCES fakultas(id);
