ALTER TABLE notifications
  MODIFY COLUMN id     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL,
  ADD CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
